spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Projet
    username: postgres
    password: admin
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
